apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:UavqsNCvOF2iTkdszMaLnXv3OoOfTq+bhhh9HhXSJpHMPzWd/uj9GNXmZ6n0M+1BuUQ8NQoW8QXt4svtwxwuvI+Yc5OeRcWdb6lY4iXfdjSSpSEERErlskpxyxpENpE9zYZLRIISvigrYSLHRqoRFVo4efeYmsxKrNtwPVAqGLVIeM2nuzg15JcxrkxPBxuVQGVoXXZ1LotVnoN7718MBe4L4eB8X4eTVGxUq77O78kXEnvlldJU/j+YOq5ESuIvzpmCKKgPfvnIDpVtJa4cgcrg3wHvA4IxldcYGf0XOycl13VZSabbEIZN2yU=,iv:CYUe2FmfSjSvljSXin2Q8H3AJ5Dh1L9CC1TcF7qDBMQ=,tag:OwMq7ZImBcPCm4vbuke1Fw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVDhZK1dpMjIvWkcvWDc0
            M2R0ZlNCQ2JwWjdHZ2xJaVpSTVNMSTZlU21rCjNsVVc4SXVLK0RsazBGRWdNMEdj
            d01VbWNRMm1xTjBVNCtvaWc4c3IvYUkKLS0tIHZMR0RyajUxQmdFUmRwaWI2WkdP
            V1Z5cUlVd3U3OE8ySnhBVlVnbmxNSjAK1VkgGpicREr1TbKPbjMQZZLB3Iu/IyzC
            IXO3BGrgJ6eF7y+6EmTh7EtE0a+HW2MGfpO4jsGcrddiuV+k177GfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T06:53:41Z"
    mac: ENC[AES256_GCM,data:1pqfSgHil3Qz8l4cYcTHaPjLkqeNnpFG2v+zs22wJDoBdykr6V6h/81Lg0eVCs9TQtE/YlBMifImaMxNrgHBRD47BFPVfGL6C/pkrapkCluaRK6P7T6FC0B3fXraVEhRLB8gMahKszcsq0AFyzSbsUS41rTJ51dImdQPkej49BU=,iv:reDaRdY0CcfNMSzRvMDl1MQ5bYqN65pCKfgkD4ypGwA=,tag:bhj7Bja/hHfpjPSMLJx6oQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
