apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:9ZHLQw9hMyRhz/uIzpnhm8xmNQViVlVXPMHPSV9z1JrN94ZiW5Ax6v6PlFcccsEF2gJkPxyKh2wnsGPo8/MU4RLFewEq3rHPTSs/XFcE9S4OOJMA6oxH+hJBQSK4Z/qbr2hRzepxd+atwatkHxNub8N8ZHRXYdcnaKCrPvJQBloEBy25wlt+JwA2nNLweU0cmlXk9A/2KRGuG1bLpyS5xRW0K8FMUbFm09DAr5nWVdnWw4FKxxu+Xdy65L0Qp2A3XgK+JrmjiLHUsNlBSffdXsQOFNE4LLeuZw6sRr8TK7RywaOL82yo0f92T9Q=,iv:JqJQWcAWhkpOZwlWXaNZWS41m/iLiWrnYjSDRwykxe0=,tag:Efjjg81wqQprs8xbm+kykg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1e8d9nf72mf7hysszaykl4yxew3eqalaw2skt6h00wavgygjq9ses7qmdza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTmpoTWFtNm5rZitCRUpM
            S2FZNFlSWFBSYkZhbUh6dXFiRjJjKzdEQ3dZCllpUW5JQW0wQ3EyV1FtQnNqNlo4
            NlRhSUtJRFhLRFQxekt3Z3BpaTJRcjAKLS0tIDEvK2poK2RYUFNtR3NmTHJkdE9K
            emRnblRHWGpIcDMvNThNWFV4U2p2dFkK3B56kr7JdKgXwwuDSTUPEw42G3Jm3hXA
            WCIlIhN5CpuR7Gkil5ZFGEIIh5Pb60RZFwlVr1eV6wbnL7UShWmX5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T09:54:56Z"
    mac: ENC[AES256_GCM,data:8Dqavkyw/VRBc1k5XxGfAd8bu0LU99DFnkXSVoia0UxwsrsUZVznawOvsFIaZGlPqMPGAMR37yh85kmKkiCpUpKRjA5QsFZ0ehK2iHX9mX7in5K/th5Y9oT2QsNPyHBnwk4W75Jzqylab7C+NO1iq3pAf7O8y1MziWOcZJE6jxY=,iv:dxN/qvrIGGFJAsjLh1GsnPOJ//dJD/ed0g8C3Bf+1JY=,tag:qp1Es0YmOHdbC7iSX1MgJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
