apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ENz0rE8Uvuh7Vym4,iv:2ifA70XKOJPsAfh/orBwNHyF4PXJmFW/yz51xIoDvdw=,tag:vB41PNHDdRlXMqFLoUm4lQ==,type:str]
    user: ENC[AES256_GCM,data:n7eFZw+odLI=,iv:VlxsYnhLVWIQDCutaEHvYV1YAq8LKqDKr7Ng6Z/3euo=,tag:O+tBuJqvQo/r9pbZl1PaqQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1xxgueqt6hemj6cscy0wjaw9wku08f6lemdxsy52x06y8hxdzw94sa0u472
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUUF2KzFjTFZyRE45TEll
            OU9oZWZXMHNYa05WYkpQa0tPdnU3aWlJRWxNCm0yakpWSWNWSjg2UHFGOVRlVVR1
            ZG0xRGdaTHFGM2xROEI1NmJFMEY5WlUKLS0tIGUvbVk4d0tyS050cmE2Nm9ET0hH
            OWxxQk8vSHhkNFJxY0lWUFFrbVd0STgKAz5RzXJiwtHvwzSqqLHTGAQpWYz5AGck
            IdV2l5+YbBMi3r+XbW5JUHW8NHHdzj9Vv376e4aOBGCeBby+9qhCnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T12:14:25Z"
    mac: ENC[AES256_GCM,data:icXi76AtzqPxEqNa532XB7KOzCEWB0llrVk/qy9/WNMOLFur4sptUZa/N125/Dw0H+3QR/fHXiEEq/MZJ/xScD2eFe5v3d9Nr/huGwLtthvmvha+Fdbqw++GnaUURWoUxZf6L6jqEdn6v1uYC1BM5wS4AlQZ2hUNVhGuRZoUpLE=,iv:36X+XbKtBXMm/3xklAdlmYkHs1GJCJ2Bpq2L8pey1Ms=,tag:0o+1Dtod9cscQAdjsy4EFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
