apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:IL+vVaxoyPj41h5vDCukIRzqMmEEJ9qoJyQvL1ovTzPkQw8iVh2svAGftT/BXtebXkxqaSw/8zpD0FH1km1CtRr51S2wdMhYk2viU97Bqd/QI9bFOSVO4xu5dOMqlhJTS50ZaBy4Rwu/UbN15qyz+TAHPVR+W0KvFfY7pUdV5Cr2DhY2hyShGdPlmusyGR2eoq0+BrCArkviIdym5yvpCvMdhU+ki4Z1pQth4gj6GPJ/hBngL5wxm/Arq9UhFXYMJAfPRjrDPuc76wUdEmGVC3Y2N1GdIlAsW0z6TE+gmAFb+SB6pKGFLJzyzPk=,iv:a7ea3AOw2CwCTPq450sVYgHQaQHvdtEZlji4wL/bzXk=,tag:1QEgnTCsNpJ3X1HdGuJzfg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNFRYSVNEaGlrMUo4ZG0v
            eWlDc0ZoN2dFLzROY3pXSXdWWGdsWjdwWG44Cko5WXhZUGdoOHN2WGR5R3pCWDZP
            WkYxTU10Z2h0dkFXMWdsWkYxZVNIOXcKLS0tIDVDNFlXYWlmc2FRVUkvRGNQTzhP
            bm1QdDVQRnlWWUl5MUJkMzJTaS9OWFUKQPl4JezN20C5Dew1D++BBQbns3XrjBmA
            kf7ybOCZ4zWlYiIy07qbtsUfBfq+sU64K617ZZNwGPrghLf4gRLCNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T06:53:41Z"
    mac: ENC[AES256_GCM,data:fxsRNmXLEXMoRm5fG+gbGmumGxT2jZATgKTsdptbAMXY93qTm27WLuVMAcz3r+E+QCUMH1CrqbXZbzed7LbSl4fHY2eNhYeN3jYLf2VurapMA+USUF2j1NoGoATcwDgE1zv5+cZ0LIcZI4t97/5QQHjiX8pb0vEh1aQX4mLAO6M=,iv:jrwmImJdhmegK0Z48A//DQnDdXzISHapFI0ZiEdBuz4=,tag:hPQGOpBmkrUdpI5r0ECEUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
