apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:YlR4rDSvRwziVbTw,iv:4Yt08HT5G7Iu7OlZwpWCUpOME/M+OqWADykPCoQQwq0=,tag:uOHOEs31HXeiwU+6JBKhDA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:HB+gB5X6bbi5hpo+xf808g==,iv:ZqhU7Hf7C1Ax8PO4tasGfwX4z+YEFnBTlpGYBkdud0U=,tag:kKPOuYyv8GJXPwPmcHdzgQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-superuser
    namespace: linkding
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHhaaTIxQzY5Qnl1SFU1
            RVh3Q2cxNnMrVTh5RHFYT3RGQjV2ZExWSVh3CnhzMUp2SWdvSk8zZk5qQTJCV1pF
            ZGtvYkUrS0l1ZGQxMC9OWGMyWCtoNDgKLS0tIHNXbHNYR1JUb1Q4ZHVzMExacXQx
            MFRSV3llLzJiNGNqK0cxcEQ1d2NySWsKc81G1hJ87MdPpwVY1txhGvNEuXoqvgbm
            8fN7UqhGeW57nwqp6r4BZpf62nBB9Cv7JfSBnXLN7DiiTS2G7wL0sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T06:53:41Z"
    mac: ENC[AES256_GCM,data:vTVRgr1DiCoall9TgYLLknzTYgPjUm4Fp89rhunZOw6+WgN2+HdoqeCZEzw7uVkN+tDQRVLJo0rWs1/Zm5YAjxnYxfrRVV1rnhpZGVNTVExqxcWhisV9anAJvzQ5wQX+QS97EypepJXR3JPbOIbITN/Bsj0zJVAUkgFwsflP/4k=,iv:eRPBUiMGRoz/p/CAWiVZncBVOUebmBAcUX//pu7USbg=,tag:R2kpMPfWHvfqpkLa4GVK0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
