apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:p5UOVDMy3Fai76XxH1psTm7q7KjsYWoOJiCsSqiBkaNAVv6/,iv:GMyCAKDUy5mEQ3zmUHJFXesq3108Ji0Iql6casbw0dk=,tag:qVfmuFEQ0OW2mGf5Ggpptw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age1f45e4rjg4f0ptw0q63t5nynsq7lcnc055fyxf5st23hlqu3ft9wqcgkmun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUnhJbUxKeW9FVWFobnNR
            QmtLMGMyZkg1ZHkxWU9zdVBIREtuR3ZYYUZzCjZmbXkvcVZ2LzZzckJrRnd3WGxp
            SWE4OVdndSsxKytuWVpXQmYyQithVDAKLS0tIHI3SThIZnN0VlNydllxanZDWDBw
            M0tCY3NKNHdPYkNkbEp3c2k0T3AyejAKRwdQawNNF632waZRmTDcvCc1zhZOCrPH
            fL4B+/lnzaBKI5QJjVXhlyyHciTtBn98XnGL7VNRpxikNv4NTCWzRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T06:55:20Z"
    mac: ENC[AES256_GCM,data:uEZO5Y2r4hrZ61uHWOOS/8KPK+hvohSzg23jYBYlwV1pVy+NkBFkGvvl+hB9gqHMpirF5h4WiK1FFmHMvEdsUo/ZUne+AuEd8zBCRdyCiGq3ZRGW/NCXTtPrxTysHNq15IINz1vjtPH3V9qZgHbz7tXcYdkfL58I6fdE5q6mABw=,iv:TYyd748hmQa0nl35OOJq9/nHty95dwz1V3ag5ULb8mQ=,tag:pDooM9+MkLJK/kSFfb303g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
